### ISSUE TITLE
Create Koa Integration with Wolf

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#104]
**Description:**
Create an integration package called `wolf-koa` which provides the glue and one or more storage implementations within the repo.

**Acceptance Criteria:**
* Create `wolf-koa` package in npm
* Create an easy to use function to integrate wolf to koa
* Create an inmemory storage implementation

**Comment by kevinleung23** [comment]
No longer necessary as our focused shifted toward implementing storage layers.
