### ISSUE TITLE
Create Express Integration with Wolf

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#105]
**Description:**
Create an integration package called `wolf-express` which provides the glue and one or more storage implementations within the repo.

**Acceptance Criteria:**
* Create `wolf-express` package in npm
* Create an easy to use function to integrate wolf to express
* Create an inmemory storage implementation

**Comment by kevinleung23** [comment]
No longer necessary as our focused shifted toward implementing storage layers.
