### ISSUE TITLE
Define Storage Interface

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#107]
**Description:**
Define a Storage Interface that can be used in all Wolf adaptors to retrieve and save the wolfState to a persistence layer.

Persistence layer implementation is defined by the user.

**Acceptance Criteria:**
* Create a Storage Interface in the wolf-core repo.

**Comment by howlowck** [comment]
Use `npm link` to import the interface typing from local version of wolf v3 to the respective wolf adaptor repos.

**Comment by kevinleung23** [comment]
Should this interface contain any other properties other than the `WolfState`?

proposed:
```js
export interface WolfStorage extends WolfState {
}
```
How the developer would utilize this:
```js
const result = wolf.run<T>(...)
const wolfStorage: WolfStorage = result.retrieveWolfState()

// developer to persist wolfStorage and make available on next turn..
```

**Comment by kevinleung23** [comment]
working on branch `storage-interface`

**Comment by kevinleung23** [comment]
Interface should contain a 'getter' and 'setter' function that the adapter/middleware will utilize. The developer is responsible for implementing these functions with their persistent layer of choice.
