### ISSUE TITLE
Define Ability Slot Connection Interface

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#109]
**Description:**
With the new separation of slots and abilities, there needs to be a way to "glue" the two concepts together.

**Acceptance Criteria:**
* The interface should be intuitive and clean
* The interface should allow the user to attach properties that is only relevant to the specific slot-ability connection.
* The resulting data structure should be able to easily answer questions such as:
  * What slots are connected to a specific ability?
  * What abilities are connected to a specific slot?
  * What properties are on the specific connection?

**Comment by kevinleung23** [comment]
Clarifying AC2: is the idea that you would define all the property functions on the slot definition `S1`, and the developer is able to create a relationship between ability `A`  and `S1`?

More-so, the developer is able to enable specific `S1` properties such as only bringing in the `query` (assume it must), `validate` and the `retry`?
The default "relationship" between `A1` and `S1` would be all slot properties, unless specific ones are identified?

**Comment by kevinleung23** [comment]
Moving back to backlog, will sync with @howlowck before continuing.
