### ISSUE TITLE
Change the Wolf Runner interface to allow multiple user `messageData`

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#128]
**Description:**
In order to support multiple user `messageData`, the runner needs to allow it.

**Acceptance Criteria:**
* allow the messageData to be an array.
* the array has to be at least one element (messageData).
* the typing (Typescript) should enforce the least-one-element array data structure for the parameter.

**Comment by kevinleung23** [comment]
Is it Wolf's concern to enforce at least one `NlpResult` element in the incoming `userMessageData` array? If Wolf's `intake` stage receives an empty array, we can default to a slot, or continue with the slot stack prompting.

I can imagine workflows that utilize Wolf as a hybrid, or an addition to additional logic.

**Comment by kevinleung23** [comment]
After a discussion with @howlowck, we are making an amend to the AC #2 and #3. It is not Wolf's responsibility to enforce at least one `nlpResult` to be passed into the array.

The developer will have to ensure there is at least one element in the array if it is in line with their logic.

If Wolf receives an empty array, we have a few options:
- Continue on an incomplete Ability
- Reference the `defaultAbility`
