### ISSUE TITLE
Implement slot history to allow for `getValue` parameter for slots.

### ISSUE THREAD

**Issue by kevinleung23** [great-lakes/botbuilder-wolf#158]
**Description:**
Before executing a slot query, we will run `getValue()` which will allow the developer to browse all of the conversation slot history. The developer can select one of the historical values to fill the slot (avoiding the need to prompt for the slot), or it can proceed with prompting the slot to get the information from the user.

To support this feature, we will need to implement a historical slot structure to make available to the user. This would be stored on `wolfState`

**Acceptance Criteria:**
- Implement a historical slot structure
- Implement the historical slot logic to populate on ever slot onFill workflow
- Expose a `getValue` property to the user on the `Trace` object
- `getValue` should be of type `async` function.
- The historical slot values is a parameter for the user defined `getValue` function
- convoStorageLayer is a parameter for `getValue`

**Comment by kevinleung23** [comment]
@howlowck please review task/AC before development starts.

**Comment by howlowck** [comment]
I also would like to user to have access to the convoStorageLayer, but this means that this getValue function needs to be async

**Comment by kevinleung23** [comment]
@howlowck I agree. Will update AC to reflect this.
