### ISSUE TITLE
[alpha] Not filling multiple slots in a single turn

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#166]
**Describe the bug**
When there are multiple slots filled during the same turn, only the first slot is being filled.

**To Reproduce**
1. Create a simple ability with two traces
2. Supply an NLPResult that filles those two slots.
3. Only the first one is filled.

**Expected behavior**
All slots should be filled

**Comment by kevinleung23** [comment]
Fixed from PR #167. This should be reflected in `alpha.11`
