### ISSUE TITLE
Acceptance Tests

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#169]
**Description:**
Creating more Acceptance Tests

**Acceptance Criteria:**
- [x] multiple slot fills in a single turn, one of the slots in the `NlpResult` overwrites a previously filled slot value
* (order pizza scenario)
* "i want a pizza and my name is Gabby" (`orderPizza` ability filling `firstName`)
* bot: "what pizza would you like?" 
* "i want a pepperoni pizza and my name is Hao" (`orderPizza` ability filling both `order` and `firstName`)

- [x] multiple slot fills in a single turn, one of the traces has a `getValue` function, that `getValue` function is not run but the new supplied value is utilized
* (order pizza scenario)
* "hi my name is Gabby" (`greet` ability filling `firstName`)
* bot: "Hello Gabby" (completes `greet` ability)
* "i want pepperoni pizza, my name is Hao" (`orderPizza` ability filling both `order` and `firstName`)

**Comment by gcrev93** [comment]
Closed with PR #180
