### ISSUE TITLE
Outtake messages are sent out of order

### ISSUE THREAD

**Issue by howlowck** [great-lakes/botbuilder-wolf#7]
**Describe the bug**
During turns when the bot is outputting multiple messages, the messages our being outputted 

**To Reproduce**
* Start the alarm bot
* "add alarm called Hao"
* "kevin"

(the messages are sometime out of order)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by KSLHacks** [comment]
fix requires use of `async await` as required by the botbuilder SDK. Outtake now returns `string[]` which the user now needs to utilize

```js
// User defined logic to display messages
      const messages: Partial<Activity>[] = messageArray.map((msg) => ({
        type: 'message',
        text: msg
      }))
      await context.sendActivities(messages)
```

**Comment by KSLHacks** [comment]
More refactor needed for better user interface, but fixes for now..
